FROM golang:1.26.1-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN go mod tidy
RUN go build -o /app/fullstack_app ./cmd

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/fullstack_app /app/fullstack_app
COPY --from=builder /app/views /app/views
COPY --from=builder /app/static /app/static

RUN mkdir -p /data /app/static/uploads

EXPOSE 8080

CMD ["/app/fullstack_app"]
